FROM python:3.6.10-slim


WORKDIR /app

RUN pip3 install \
        six \
        bs4 \
        redis \
        django \
        pytest \
        ipcalc \
        demjson \
        requests \
        botocore \
        virtualenv \
        mongoengine